-- ==========================================================
-- WALMART PROJECT – MySQL
-- ==========================================================

/* ------------------------------------------------------------------------
   BUSINESS QUESTIONS & INSIGHTS (GROUPED BY CATEGORY)
------------------------------------------------------------------------ */



/* =========================================================================
   CATEGORY A: SALES & REVENUE ANALYSIS
   ========================================================================= */


/* ========================================================================
   Q1: Analyze Payment Methods and Sales
      What are the different payment methods, and how many transactions and 
      items were sold with each?
   ======================================================================== */

SELECT 
    payment_method,
    COUNT(*) AS no_of_transactions,
    SUM(quantity) AS total_qty_sold
FROM walmart_db.walmart
GROUP BY payment_method;



/* ========================================================================
   Q2: Total Quantity Sold by Payment Method
      How many items were sold through each payment method?
   ======================================================================== */

SELECT 
    payment_method,
    SUM(quantity) AS total_quantity_sold
FROM walmart_db.walmart
GROUP BY payment_method;



/* ========================================================================
   Q3: Best-Selling Category per Branch
      Which category sells the most in each branch?
   ======================================================================== */

WITH category_sales AS (
    SELECT 
        branch,
        category,
        SUM(quantity) AS total_qty,
        RANK() OVER(PARTITION BY branch ORDER BY SUM(quantity) DESC) AS rnk
    FROM walmart_db.walmart
    GROUP BY branch, category
)
SELECT branch, category, total_qty
FROM category_sales
WHERE rnk = 1;



/* ========================================================================
   Q4: Revenue Contribution by Category
      What percentage of revenue does each category contribute?
   ======================================================================== */

WITH total_rev AS (
    SELECT SUM(total_amount) AS grand_total
    FROM walmart_db.walmart
)
SELECT 
    category,
    SUM(total_amount) AS category_revenue,
    ROUND((SUM(total_amount) / (SELECT grand_total FROM total_rev)) * 100, 2) 
        AS revenue_percentage
FROM walmart_db.walmart
GROUP BY category
ORDER BY revenue_percentage DESC;



/* ========================================================================
   Q5: Average Basket Size
      What is the average number of items per invoice?
   ======================================================================== */

SELECT 
    ROUND(AVG(quantity), 2) AS avg_items_per_invoice
FROM walmart_db.walmart;



/* ========================================================================
   Q6: Highest Revenue Day per Month
      Which day of each month generated the highest revenue?
   ======================================================================== */

WITH daily_sales AS (
    SELECT 
        DATE(date) AS day,
        MONTH(date) AS month_no,
        SUM(total_amount) AS revenue,
        RANK() OVER(PARTITION BY MONTH(date) ORDER BY SUM(total_amount) DESC) AS rnk
    FROM walmart_db.walmart
    GROUP BY DATE(date), MONTH(date)
)
SELECT month_no, day, revenue
FROM daily_sales
WHERE rnk = 1
ORDER BY month_no;



/* ========================================================================
   Q7: Total Profit by Category
      What is the total profit generated by each category?
   ======================================================================== */

SELECT 
    category,
    SUM(total_amount * profit_margin) AS total_profit
FROM walmart_db.walmart
GROUP BY category
ORDER BY total_profit DESC;




/* =========================================================================
   CATEGORY B: RATINGS, PROFIT & QUALITY INSIGHTS
   ========================================================================= */


/* ========================================================================
   Q8: Highest-Rated Category in Each Branch
      Which category received the highest average rating in each branch?
   ======================================================================== */

WITH cte AS (
    SELECT 
        branch, 
        category, 
        AVG(rating) AS avg_rating,
        RANK() OVER (PARTITION BY branch ORDER BY AVG(rating) DESC) AS `rank`
    FROM walmart_db.walmart
    GROUP BY branch, category
)
SELECT 
    branch,
    category,
    avg_rating
FROM cte
WHERE `rank` = 1;



/* ========================================================================
   Q9: Category Ratings by City
      What are the average, minimum, and maximum ratings for each 
      category in each city?
   ======================================================================== */

SELECT 
    city,
    category,
    AVG(rating) AS avg_rating,
    MIN(rating) AS min_rating,
    MAX(rating) AS max_rating
FROM walmart_db.walmart
GROUP BY city, category;



/* ========================================================================
   Q10: Rating vs Sales Analysis
      Which categories have high sales but low ratings?
   ======================================================================== */

SELECT 
    category,
    ROUND(AVG(rating), 2) AS avg_rating,
    SUM(total_amount) AS total_revenue
FROM walmart_db.walmart
GROUP BY category
ORDER BY avg_rating ASC, total_revenue DESC;



/* ========================================================================
   Q11: Profit by Branch
      Which branches generate the most profit?
   ======================================================================== */

SELECT 
    branch,
    SUM(total_amount * profit_margin) AS total_profit
FROM walmart_db.walmart
GROUP BY branch
ORDER BY total_profit DESC;




/* =========================================================================
   CATEGORY C: BRANCH & TIME-BASED OPERATIONAL INSIGHTS
   ========================================================================= */


/* ========================================================================
   Q12: Busiest Day for Each Branch
      Which day of the week has the highest transaction count in each branch?
   ======================================================================== */

SELECT 
    branch,
    day_name,
    no_of_transactions
FROM (
    SELECT 
        branch,
        DAYNAME(date) AS day_name,
        COUNT(*) AS no_of_transactions,
        RANK() OVER (
            PARTITION BY branch 
            ORDER BY COUNT(*) DESC
        ) AS `rank`
    FROM walmart_db.walmart
    GROUP BY branch, day_name
) AS ranked
WHERE `rank` = 1;



/* ========================================================================
   Q13: Most Common Payment Method per Branch
      Which payment method is most frequently used in each branch?
   ======================================================================== */

WITH payment_counts AS (
    SELECT 
        branch,
        payment_method,
        COUNT(*) AS total_transactions,
        RANK() OVER (
            PARTITION BY branch 
            ORDER BY COUNT(*) DESC
        ) AS payment_rank
    FROM walmart_db.walmart
    GROUP BY branch, payment_method
)
SELECT 
    branch,
    payment_method,
    total_transactions
FROM payment_counts
WHERE payment_rank = 1;



/* ========================================================================
   Q14: Sales by Shift
      How many transactions occur in Morning, Afternoon, Evening, Night?
   ======================================================================== */

SELECT 
    branch,
    CASE 
        WHEN EXTRACT(HOUR FROM time) BETWEEN 6 AND 11 THEN 'Morning'
        WHEN EXTRACT(HOUR FROM time) BETWEEN 12 AND 17 THEN 'Afternoon'
        WHEN EXTRACT(HOUR FROM time) BETWEEN 18 AND 21 THEN 'Evening'
        ELSE 'Night'
    END AS shift,
    COUNT(*) AS total_transactions,
    SUM(total_amount) AS total_sales
FROM walmart_db.walmart
GROUP BY branch, shift
ORDER BY branch, total_sales DESC;



/* ========================================================================
   Q15: Branch Revenue Decline YoY
      Which branches experienced the highest revenue decrease YoY?
   ======================================================================== */

WITH revenue_2022 AS (
    SELECT 
        branch,
        SUM(total_amount) AS revenue_2022
    FROM walmart_db.walmart
    WHERE YEAR(date) = 2022
    GROUP BY branch
),
revenue_2023 AS (
    SELECT 
        branch,
        SUM(total_amount) AS revenue_2023
    FROM walmart_db.walmart
    WHERE YEAR(date) = 2023
    GROUP BY branch
)
SELECT 
    r22.branch,
    r22.revenue_2022 AS last_year_revenue,
    r23.revenue_2023 AS current_year_revenue,
    ROUND(((r22.revenue_2022 - r23.revenue_2023) / r22.revenue_2022) * 100, 2) 
        AS revenue_decrease_ratio
FROM revenue_2022 AS r22
JOIN revenue_2023 AS r23 
    ON r22.branch = r23.branch
WHERE r22.revenue_2022 > r23.revenue_2023
ORDER BY revenue_decrease_ratio DESC
LIMIT 5;

